name: P7pro
favicon: null
layout_spectrum: 0.76003
typography_spectrum: 0.75386
title: P7 pro Contract Logistics
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.46645768196322024
  lightness: 0.3833059936296195
  saturation: 0.18524154764600098
  rhythmicContrast: 0.7496332118753344
purpose: []
